import type { Metadata } from 'next';
import { Outfit } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import './globals.css';


const outfit = Outfit({
	subsets: ['latin']
})
export const metadata: Metadata = {
	title: 'Bimo',
	description: 'Generated by create next app',
	icons: "code.svg"
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();

	return (
		<html lang={locale} className={outfit.className}>
			<body>
				<NextIntlClientProvider>
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
